---
include:
 - board: xiao_ble/nrf52840/zmk
   shield: zonkey_R rgbled_adapter
   snippet: studio-rpc-usb-uart
 - board: xiao_ble/nrf52840/zmk
   shield: zonkey_L tom_oled rgbled_adapter
 - board: xiao_ble/nrf52840/zmk
   shield: settings_reset
