manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: sekigon-gonnoc
      url-base: https://github.com/sekigon-gonnoc
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: iwk7273
      url-base: https://github.com/iwk7273
    - name: caksoylar
      url-base: https://github.com/caksoylar

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk-feature-non-lipo-battery-management
      remote: sekigon-gonnoc
      revision: main

    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main

    - name: zmk-feature-xy_clipper
      remote: iwk7273
      revision: main

    /* ----------------------------------------------------------------------
       エラーを100%回避するため、リモート名を使わず、直接GitHubのURLを指定しました
       ---------------------------------------------------------------------- */
    - name: zmk-tom-oled
      url: https://github.com
      revision: zephyr-4.1 

    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main

  self:
    path: config
