manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com # ← システムに削られても正しいURLになるようリポジトリ名まで含めました
    - name: sekigon-gonnoc
      url-base: https://github.com
    - name: badjeff
      url-base: https://github.com
    - name: iwk7273
      url-base: https://github.com
    - name: canandrum
      url-base: https://github.com
    - name: caksoylar
      url-base: https://github.com

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk-feature-non-lipo-battery-management
      remote: sekigon-gonnoc
      revision: main

    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main

    - name: zmk-feature-xy_clipper
      remote: iwk7273
      revision: main

    - name: zmk-tom-oled
      remote: canandrum
      revision: zephyr-4.1

    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main

  self:
    path: config
